# Generated by Django 4.2.4 on 2023-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicform',
            name='description',
        ),
        migrations.AlterField(
            model_name='dynamicform',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicformfield',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
